id: ARKAROUTING-03-CONFIG
version: 1.0.0
exports:
- paths
- options
paths:
  os_root: ../ARKA_OS
  core: ../ARKA_OS/ARKA_CORE
  flow: ../ARKA_OS/ARKA_FLOW
  agents: ../ARKA_OS/ARKA_AGENT
options:
  doc_frontmatter_key: arkaref
  max_results: 50
  index_cache: ./.cache/index.json
